packages:
  - sdk
  - playgrounds/*

catalog:
  0xsequence: ^2.3.23
  '@0xsequence/api': ^2.3.23
  '@0xsequence/checkout': ^5.3.12
  '@0xsequence/connect': ^5.3.12
  '@0xsequence/design-system': ^2.2.1
  '@0xsequence/hooks': ^5.3.12
  '@0xsequence/indexer': ^2.3.23
  '@0xsequence/metadata': ^2.3.23
  '@0xsequence/network': ^2.3.23
  '@0xsequence/wallet-widget': ^5.3.12
  '@arethetypeswrong/cli': ^0.18.2
  '@biomejs/biome': ^2.2.0
  '@changesets/cli': ^2.29.6
  '@google/model-viewer': ^4.1.0
  '@legendapp/state': 3.0.0-beta.31
  '@tanstack/react-query': ^5.85.3
  '@tanstack/react-query-devtools': ^5.85.3
  '@types/react': ^19.1.10
  '@0xtrails': ^0.1.1
  '@types/react-dom': ^19.1.7
  '@xstate/store': ^3.8.5
  ctix: ^2.7.1
  date-fns: ^4.1.0
  dnum: ^2.15.0
  nuqs: ^2.4.3
  react: ^19.1.1
  react-day-picker: ^9.9.0
  react-dom: ^19.1.1
  tailwindcss: ^4.1.12
  tsup: ^8.5.0
  typescript: ^5.9.2
  viem: ^2.34.0
  vite: ^7.1.2
  vite-tsconfig-paths: ^5.1.4
  wagmi: ^2.16.3

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - msw
