packages:
  - sdk
  - playgrounds/*

catalog:
  '@0xsequence/api': ^2.3.23
  '@0xsequence/design-system': ^2.1.15
  '@0xsequence/indexer': ^2.3.23
  '@0xsequence/metadata': ^2.3.23
  '@0xsequence/network': ^2.3.23
  '@arethetypeswrong/cli': ^0.18.2
  '@biomejs/biome': ^2.1.3
  '@changesets/cli': ^2.29.5
  '@legendapp/state': 3.0.0-beta.31
  '@tanstack/react-query': ^5.84.1
  '@tanstack/react-query-devtools': ^5.84.1
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@0xsequence/connect': ^5.3.9
  '@0xsequence/wallet-widget': ^5.3.9
  '@0xsequence/checkout': ^5.3.9
  '@0xsequence/hooks': ^5.3.9
  '@xstate/store': ^3.8.4
  '@google/model-viewer': ^4.1.0
  0xsequence: ^2.3.23
  ctix: ^2.7.1
  date-fns: ^4.1.0
  react: ^19.1.1
  react-day-picker: ^9.8.1
  react-dom: ^19.1.1
  tsup: ^8.5.0
  typescript: ^5.9.2
  viem: ^2.33.2
  vite: ^7.0.6
  vite-tsconfig-paths: ^5.1.4
  wagmi: ^2.16.1
  tailwindcss: ^4.1.11
  dnum: ^2.15.0
  nuqs: ^2.4.3

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - msw
