packages:
  - sdk
  - playgrounds/*

catalog:
  0xsequence: ^2.3.32
  '@0xsequence/api': ^2.3.33
  '@0xsequence/checkout': ^5.4.0
  '@0xsequence/connect': ^5.4.0
  '@0xsequence/design-system': ^2.2.5
  '@0xsequence/hooks': ^5.4.0
  '@0xsequence/indexer': ^2.3.33
  '@0xsequence/metadata': ^2.3.33
  '@0xsequence/network': ^2.3.33
  '@0xsequence/wallet-widget': ^5.4.0
  '@arethetypeswrong/cli': ^0.18.2
  '@biomejs/biome': ^2.3.1
  '@changesets/cli': ^2.29.7
  '@google/model-viewer': ^4.1.0
  '@legendapp/state': 3.0.0-beta.32
  '@tanstack/react-query': ^5.90.5
  '@tanstack/react-query-devtools': ^5.90.2
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@xstate/store': ^3.11.2
  ctix: ^2.7.1
  date-fns: ^4.1.0
  dnum: ^2.15.0
  nuqs: ^2.7.2
  react: ^19.2.0
  react-day-picker: ^9.11.1
  react-dom: ^19.2.0
  tailwindcss: ^4.1.16
  tsup: ^8.5.0
  typescript: ^5.9.3
  viem: ^2.38.5
  vite: ^7.1.12
  vite-tsconfig-paths: ^5.1.4
  wagmi: ^2.19.0

ignoredBuiltDependencies:
  - sharp

minimumReleaseAge: 20160

minimumReleaseAgeExclude:
  - '@0xsequence/*'
  - sequence

onlyBuiltDependencies:
  - msw
