packages:
  - packages/*
  - playgrounds/*
catalog:
  '@0xsequence/api': ^2.2.14
  '@0xsequence/design-system': ^2.0.9
  '@0xsequence/indexer': ^2.2.14
  '@0xsequence/kit': 0.0.0-20250305153405
  '@0xsequence/kit-checkout': 0.0.0-20250305153405
  '@0xsequence/metadata': ^2.2.14
  '@0xsequence/network': ^2.2.14
  '@arethetypeswrong/cli': ^0.17.4
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.28.1
  '@legendapp/state': ^3.0.0-beta.30
  '@radix-ui/react-dialog': ^1.1.6
  '@radix-ui/react-popover': ^1.1.6
  '@radix-ui/react-select': ^2.1.6
  '@tanstack/react-query': ^5.67.2
  '@tanstack/react-query-devtools': ^5.67.2
  '@types/react': ^18.3.18
  '@types/react-dom': ^18.3.5
  '@vanilla-extract/css': ^1.17.1
  '@vanilla-extract/esbuild-plugin': ^2.3.15
  '@vanilla-extract/recipes': ^0.5.5
  '@vanilla-extract/vite-plugin': ^5.0.1
  0xsequence: ^2.2.14
  ctix: ^2.7.0
  date-fns: ^4.1.0
  react: ^18.3.1
  react-day-picker: ^9.6.1
  react-dom: ^18.3.1
  rimraf: ^6.0.1
  tsup: ^8.4.0
  typescript: ^5.8.2
  viem: ^2.23.9
  vite: ^6.2.1
  vite-tsconfig-paths: ^5.1.4
  wagmi: ^2.14.12
  zod: ^3.24.2
