packages:
  - sdk
  - playgrounds/*
  - infra

catalog:
  0xsequence: ^2.3.25
  0xtrails: ^0.1.5
  '@0xsequence/api': ^2.3.25
  '@0xsequence/checkout': ^5.3.14
  '@0xsequence/connect': ^5.3.14
  '@0xsequence/design-system': ^2.2.2
  '@0xsequence/hooks': ^5.3.14
  '@0xsequence/indexer': ^2.3.25
  '@0xsequence/metadata': ^2.3.25
  '@0xsequence/network': ^2.3.25
  '@0xsequence/wallet-widget': ^5.3.14
  '@arethetypeswrong/cli': ^0.18.2
  '@biomejs/biome': ^2.2.4
  '@changesets/cli': ^2.29.6
  '@google/model-viewer': ^4.1.0
  '@legendapp/state': 3.0.0-beta.32
  '@tanstack/react-query': ^5.85.6
  '@tanstack/react-query-devtools': ^5.85.6
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  '@xstate/store': ^3.9.2
  ctix: ^2.7.1
  date-fns: ^4.1.0
  dnum: ^2.15.0
  react: ^19.1.1
  react-day-picker: ^9.9.0
  react-dom: ^19.1.1
  tailwindcss: ^4.1.12
  tsup: ^8.5.0
  typescript: ^5.9.2
  viem: ^2.36.0
  vite: ^7.1.4
  vite-tsconfig-paths: ^5.1.4
  wagmi: 2.16.9

overrides:
  wagmi: 2.16.9

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - msw
