packages:
  - api
  - sdk
  - playgrounds/*

catalog:
  0xsequence: 2.3.38
  '@0xsequence/api': 2.3.38
  '@0xsequence/checkout': ^5.4.8
  '@0xsequence/connect': ^5.4.8
  '@0xsequence/design-system': ^3.1.7
  '@0xsequence/hooks': ^5.4.8
  '@0xsequence/indexer': 2.3.38
  '@0xsequence/metadata': 2.3.38
  '@0xsequence/network': 2.3.38
  '@0xsequence/waas': 2.3.38
  '@0xsequence/wallet-widget': ^5.4.8
  '@arethetypeswrong/cli': ^0.18.2
  '@biomejs/biome': ^2.3.10
  '@changesets/cli': ^2.29.8
  '@eslint/js': ^9.39.2
  '@google/model-viewer': ^4.1.0
  '@tanstack/react-query': 5.90.9
  '@tanstack/react-query-devtools': ^5.91.2
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@xstate/store': ^3.14.0
  ctix: ^2.7.1
  date-fns: ^4.1.0
  dnum: ^2.17.0
  eslint: ^9.39.2
  eslint-config-biome: ^2.1.3
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-storybook: ^10.1.11
  globals: ^16.5.0
  nuqs: ^2.8.6
  react: ^19.2.3
  react-day-picker: ^9.13.0
  react-dom: ^19.2.3
  tailwindcss: ^4.1.18
  tsup: ^8.5.1
  typescript: ^5.9.3
  typescript-eslint: ^8.51.0
  viem: 2.41.2
  vite: ^7.3.0
  vite-tsconfig-paths: ^6.0.3
  wagmi: 2.18.0

ignoredBuiltDependencies:
  - sharp

minimumReleaseAge: 20160

minimumReleaseAgeExclude:
  - viem
  - '@0xsequence/*'
  - '@0xtrails/*'
  - 0xtrails
  - 0xsequence

onlyBuiltDependencies:
  - msw
