packages:
  - packages/*
  - playgrounds/*
catalog:
  '@0xsequence/api': ^2.2.14
  '@0xsequence/design-system': ^2.0.10
  '@0xsequence/indexer': ^2.2.14
  '@0xsequence/metadata': ^2.2.14
  '@0xsequence/network': ^2.2.14
  '@arethetypeswrong/cli': ^0.17.4
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.28.1
  '@legendapp/state': ^3.0.0-beta.30
  '@tanstack/react-query': ^5.68.0
  '@tanstack/react-query-devtools': ^5.68.0
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.4
  '@0xsequence/react-checkout': ^0.0.0-20250312201716
  '@0xsequence/react-connect': ^0.0.0-20250312201716
  '@0xsequence/react-wallet': ^0.0.0-20250312201716
  0xsequence: ^2.2.14
  ctix: ^2.7.0
  date-fns: ^4.1.0
  react: ^19.0.0
  react-day-picker: ^9.6.2
  react-dom: ^19.0.0
  rimraf: ^6.0.1
  tsup: ^8.4.0
  typescript: ^5.8.2
  viem: ^2.23.11
  vite: ^6.2.2
  vite-tsconfig-paths: ^5.1.4
  wagmi: ^2.14.13
  zod: ^3.24.2
  tailwindcss: ^4.0.14
  dnum: ^2.14.0
onlyBuiltDependencies:
  - msw
ignoredBuiltDependencies:
  - sharp

