packages:
  - sdk
  - playgrounds/*

catalog:
  '@0xsequence/api': ^2.3.20
  '@0xsequence/design-system': ^2.1.15
  '@0xsequence/indexer': ^2.3.20
  '@0xsequence/metadata': ^2.3.20
  '@0xsequence/network': ^2.3.20
  '@arethetypeswrong/cli': ^0.18.2
  '@biomejs/biome': ^2.0.5
  '@changesets/cli': ^2.29.5
  '@legendapp/state': 3.0.0-beta.31
  '@tanstack/react-query': ^5.81.2
  '@tanstack/react-query-devtools': ^5.81.2
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@0xsequence/connect': ^5.3.6
  '@0xsequence/wallet-widget': ^5.3.6
  '@0xsequence/checkout': ^5.3.6
  '@0xsequence/hooks': ^5.3.6
  '@xstate/store': ^3.7.0
  '@google/model-viewer': ^4.1.0
  0xsequence: ^2.3.20
  ctix: ^2.7.1
  date-fns: ^4.1.0
  react: ^19.1.0
  react-day-picker: ^9.7.0
  react-dom: ^19.1.0
  tsup: ^8.5.0
  typescript: ^5.8.3
  viem: ^2.31.4
  vite: ^7.0.0
  vite-tsconfig-paths: ^5.1.4
  wagmi: ^2.15.6
  tailwindcss: ^4.1.10
  dnum: ^2.15.0
  nuqs: ^2.4.3

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - msw
