packages:
  - sdk
  - playgrounds/*
catalog:
  '@0xsequence/api': ^2.3.8
  '@0xsequence/design-system': ^2.1.6
  '@0xsequence/indexer': ^2.3.8
  '@0xsequence/metadata': ^2.3.8
  '@0xsequence/network': ^2.3.8
  '@arethetypeswrong/cli': ^0.17.4
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.29.0
  '@legendapp/state': ^3.0.0-beta.30
  '@tanstack/react-query': ^5.74.3
  '@tanstack/react-query-devtools': ^5.74.3
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.2
  '@0xsequence/connect': ^5.1.1
  '@0xsequence/wallet-widget': ^5.1.1
  '@0xsequence/checkout': ^5.1.1
  '@xstate/store': ^3.4.3
  0xsequence: ^2.3.8
  ctix: ^2.7.1
  date-fns: ^4.1.0
  react: ^19.1.0
  react-day-picker: ^9.6.7
  react-dom: ^19.1.0
  tsup: ^8.4.0
  typescript: ^5.8.3
  viem: ^2.27.0
  vite: ^6.2.6
  vite-tsconfig-paths: ^5.1.4
  wagmi: ^2.14.16
  zod: ^3.24.2
  tailwindcss: ^4.1.4
  dnum: ^2.14.0
onlyBuiltDependencies:
  - msw
ignoredBuiltDependencies:
  - sharp
