packages:
  - sdk
  - playgrounds/*

catalog:
  '@0xsequence/api': ^2.3.17
  '@0xsequence/design-system': ^2.1.14
  '@0xsequence/indexer': ^2.3.17
  '@0xsequence/metadata': ^2.3.17
  '@0xsequence/network': ^2.3.17
  '@arethetypeswrong/cli': ^0.18.1
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.29.4
  '@legendapp/state': ^3.0.0-beta.31
  '@tanstack/react-query': ^5.80.6
  '@tanstack/react-query-devtools': ^5.80.6
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.6
  '@0xsequence/connect': ^5.3.4
  '@0xsequence/wallet-widget': ^5.3.4
  '@0xsequence/checkout': ^5.3.4
  '@0xsequence/hooks': ^5.3.4
  '@xstate/store': ^3.6.2
  '@google/model-viewer': ^4.1.0
  0xsequence: ^2.3.17
  ctix: ^2.7.1
  date-fns: ^4.1.0
  react: ^19.1.0
  react-day-picker: ^9.7.0
  react-dom: ^19.1.0
  tsup: ^8.5.0
  typescript: ^5.8.3
  viem: ^2.31.0
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  wagmi: ^2.15.6
  zod: ^3.25.56
  tailwindcss: ^4.1.8
  dnum: ^2.15.0
  nuqs: ^2.4.3

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - msw
