packages:
  - packages/*
  - playgrounds/*
catalog:
  '@0xsequence/api': ^2.0.25
  '@0xsequence/design-system': ^1.7.8
  '@0xsequence/indexer': ^2.0.25
  '@0xsequence/kit': ^4.4.4
  '@0xsequence/kit-checkout': ^4.4.4
  '@0xsequence/metadata': ^2.0.25
  '@0xsequence/network': ^2.0.25
  '@tanstack/react-query': 5.59.14
  '@tanstack/react-query-devtools': ^5.59.20
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  '@vanilla-extract/css': ^1.16.0
  '@vanilla-extract/esbuild-plugin': ^2.3.11
  '@vanilla-extract/recipes': ^0.5.5
  '@vanilla-extract/vite-plugin': ^4.0.17
  typescript: ^5.6.3
  react: ^18.3.1
  react-dom: ^18.3.1
  viem: ^2.21.44
  wagmi: ^2.12.29
