packages:
  - sdk
  - playgrounds/*
catalog:
  '@0xsequence/api': ^2.3.4
  '@0xsequence/design-system': ^2.1.5
  '@0xsequence/indexer': ^2.3.4
  '@0xsequence/metadata': ^2.3.4
  '@0xsequence/network': ^2.3.4
  '@arethetypeswrong/cli': ^0.17.4
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.28.1
  '@legendapp/state': ^3.0.0-beta.30
  '@tanstack/react-query': ^5.71.1
  '@tanstack/react-query-devtools': ^5.71.1
  '@types/react': ^19.0.12
  '@types/react-dom': ^19.0.4
  '@0xsequence/connect': ^5.0.8
  '@0xsequence/wallet-widget': ^5.0.8
  '@0xsequence/checkout': ^5.0.8
  0xsequence: ^2.3.4
  ctix: ^2.7.0
  date-fns: ^4.1.0
  react: ^19.1.0
  react-day-picker: ^9.6.4
  react-dom: ^19.1.0
  tsup: ^8.4.0
  typescript: ^5.8.2
  viem: ^2.24.3
  vite: ^6.2.4
  vite-tsconfig-paths: ^5.1.4
  wagmi: ^2.14.16
  zod: ^3.24.2
  tailwindcss: ^4.0.17
  dnum: ^2.14.0
onlyBuiltDependencies:
  - msw
ignoredBuiltDependencies:
  - sharp
