#!/bin/bash

SCRIPT_DIR=$(dirname "$0")

# Extract version from package.json
VERSION=$(jq -r .version "$SCRIPT_DIR/package.json")
echo "// This file is auto-generated by copy-version.sh
export const VERSION = '$VERSION';" > "$SCRIPT_DIR/src/version.ts"
