// Re-export all functions from the actual nuqs package
import {
  createSerializer,
  createParser,
  parseAsString,
  parseAsInteger,
  parseAsFloat,
  parseAsBoolean,
  parseAsJson,
  parseAsArrayOf,
  parseAsStringEnum,
  parseAsStringLiteral,
  parseAsNumberLiteral,
  parseAsTimestamp,
  parseAsIsoDateTime,
  parseAsIsoDate,
  parseAsHex,
  parseAsIndex,
  useQueryState,
  useQueryStates,
  createLoader,
  createStandardSchemaV1,
  debounce,
  throttle,
  defaultRateLimit
} from 'nuqs';

export {
  createSerializer,
  createParser,
  parseAsString,
  parseAsInteger,
  parseAsFloat,
  parseAsBoolean,
  parseAsJson,
  parseAsArrayOf,
  parseAsStringEnum,
  parseAsStringLiteral,
  parseAsNumberLiteral,
  parseAsTimestamp,
  parseAsIsoDateTime,
  parseAsIsoDate,
  parseAsHex,
  parseAsIndex,
  useQueryState,
  useQueryStates,
  createLoader,
  createStandardSchemaV1,
  debounce,
  throttle,
  defaultRateLimit
};
