// Relevant parts for lookupMarketplace & common Webrpc utilities
// sequence-builder v0.1.0 52bd730f3b821fe99051d69ced824442369efe4a
// --
// Code generated by webrpc-gen@v0.26.0 with typescript generator. DO NOT EDIT.
//
// webrpc-gen -schema=builder.main.ridl -target=typescript -client -out=../../webapp/src/rpc/proto/builder.gen.ts

export const WebrpcHeader = 'Webrpc';
export const WebrpcHeaderValue =
	'webrpc@v0.26.0;gen-typescript@v0.17.0;sequence-builder@v0.1.0';

//
// Types for lookupMarketplace
//

export enum MarketplaceWalletType {
	UNIVERSAL = 'UNIVERSAL',
	EMBEDDED = 'EMBEDDED',
	ECOSYSTEM = 'ECOSYSTEM',
}

export enum FilterCondition {
	ENTIRE_KEY = 'ENTIRE_KEY',
	SPECIFIC_VALUE = 'SPECIFIC_VALUE',
}

export interface LookupMarketplaceArgs {
	projectId?: number;
	domain?: string;
	userAddress?: string;
}

export interface LookupMarketplaceReturn {
	marketplace: Marketplace;
	marketCollections: Array<MarketCollection>;
	shopCollections: Array<ShopCollection>;
}

export interface Marketplace {
	projectId: number;
	settings: MarketplaceSettings;
	market: MarketplacePage;
	shop: MarketplacePage;
	createdAt?: string;
	updatedAt?: string;
}

export interface MarketplaceSettings {
	style: { [key: string]: any };
	publisherId: string;
	title: string;
	socials: MarketplaceSocials;
	faviconUrl: string;
	walletOptions: MarketplaceWallet;
	logoUrl: string;
	fontUrl: string;
	accessKey?: string;
}

export interface MarketplacePage {
	enabled: boolean;
	bannerUrl: string;
	ogImage: string;
	private: boolean;
}

export interface MarketplaceSocials {
	twitter: string;
	discord: string;
	website: string;
	tiktok: string;
	instagram: string;
	youtube: string;
}

export interface MarketplaceWallet {
	walletType: MarketplaceWalletType;
	oidcIssuers: { [key: string]: string };
	connectors: Array<string>;
	includeEIP6963Wallets: boolean;
	ecosystem?: MarketplaceWalletEcosystem;
	embedded?: MarketplaceWalletEmbedded;
}

export interface MarketplaceWalletEcosystem {
	walletUrl: string;
	walletAppName: string;
	logoLightUrl?: string;
	logoDarkUrl?: string;
}

export interface MarketplaceWalletEmbedded {
	tenantKey: string;
	emailEnabled: boolean;
	providers: Array<OpenIdProvider>;
}

export interface OpenIdProvider {
	iss: string;
	aud: Array<string>;
}

export interface MarketCollection {
	id: number;
	projectId: number;
	chainId: number;
	itemsAddress: string;
	contractType: string;
	bannerUrl: string;
	feePercentage: number;
	currencyOptions: Array<string>;
	destinationMarketplace: string;
	filterSettings?: CollectionFilterSettings;
	sortOrder?: number;
	private: boolean;
	createdAt?: string;
	updatedAt?: string;
}

export interface CollectionFilterSettings {
	filterOrder: Array<string>;
	exclusions: Array<MetadataFilterRule>;
}

export interface MetadataFilterRule {
	key: string;
	condition: FilterCondition;
	value?: string;
}

export interface ShopCollection {
	id: number;
	projectId: number;
	chainId: number;
	itemsAddress: string;
	saleAddress: string;
	name: string;
	bannerUrl: string;
	tokenIds: Array<string>;
	customTokenIds: Array<string>;
	sortOrder?: number;
	private: boolean;
	createdAt?: string;
	updatedAt?: string;
}

//
// Service Interface Definition for MarketplaceService (relevant part)
//
export interface MarketplaceService {
	/**
	 * Public Methods
	 */
	lookupMarketplace(
		args: LookupMarketplaceArgs,
		headers?: object,
		signal?: AbortSignal,
	): Promise<LookupMarketplaceReturn>;
}

//
// Errors (Complete set from original)
//

export class WebrpcError extends Error {
	name: string;
	code: number;
	message: string;
	status: number;
	cause?: string;

	/** @deprecated Use message instead of msg. Deprecated in webrpc v0.11.0. */
	msg: string;

	constructor(
		name: string,
		code: number,
		message: string,
		status: number,
		cause?: string,
	) {
		super(message);
		this.name = name || 'WebrpcError';
		this.code = typeof code === 'number' ? code : 0;
		this.message = message || `endpoint error ${this.code}`;
		this.msg = this.message;
		this.status = typeof status === 'number' ? status : 0;
		this.cause = cause;
		Object.setPrototypeOf(this, WebrpcError.prototype);
	}

	static new(payload: any): WebrpcError {
		return new WebrpcError(
			payload.error,
			payload.code,
			payload.message || payload.msg,
			payload.status,
			payload.cause,
		);
	}
}

// Webrpc errors

export class WebrpcEndpointError extends WebrpcError {
	constructor(
		name = 'WebrpcEndpoint',
		code = 0,
		message = 'endpoint error',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, WebrpcEndpointError.prototype);
	}
}

export class WebrpcRequestFailedError extends WebrpcError {
	constructor(
		name = 'WebrpcRequestFailed',
		code = -1,
		message = 'request failed',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, WebrpcRequestFailedError.prototype);
	}
}

export class WebrpcBadRouteError extends WebrpcError {
	constructor(
		name = 'WebrpcBadRoute',
		code = -2,
		message = 'bad route',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, WebrpcBadRouteError.prototype);
	}
}

export class WebrpcBadMethodError extends WebrpcError {
	constructor(
		name = 'WebrpcBadMethod',
		code = -3,
		message = 'bad method',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, WebrpcBadMethodError.prototype);
	}
}

export class WebrpcBadRequestError extends WebrpcError {
	constructor(
		name = 'WebrpcBadRequest',
		code = -4,
		message = 'bad request',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, WebrpcBadRequestError.prototype);
	}
}

export class WebrpcBadResponseError extends WebrpcError {
	constructor(
		name = 'WebrpcBadResponse',
		code = -5,
		message = 'bad response',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, WebrpcBadResponseError.prototype);
	}
}

export class WebrpcServerPanicError extends WebrpcError {
	constructor(
		name = 'WebrpcServerPanic',
		code = -6,
		message = 'server panic',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, WebrpcServerPanicError.prototype);
	}
}

export class WebrpcInternalErrorError extends WebrpcError {
	// Name as per original
	constructor(
		name = 'WebrpcInternalError',
		code = -7,
		message = 'internal error',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, WebrpcInternalErrorError.prototype);
	}
}

export class WebrpcClientDisconnectedError extends WebrpcError {
	constructor(
		name = 'WebrpcClientDisconnected',
		code = -8,
		message = 'client disconnected',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, WebrpcClientDisconnectedError.prototype);
	}
}

export class WebrpcStreamLostError extends WebrpcError {
	constructor(
		name = 'WebrpcStreamLost',
		code = -9,
		message = 'stream lost',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, WebrpcStreamLostError.prototype);
	}
}

export class WebrpcStreamFinishedError extends WebrpcError {
	constructor(
		name = 'WebrpcStreamFinished',
		code = -10,
		message = 'stream finished',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, WebrpcStreamFinishedError.prototype);
	}
}

// Schema errors

export class UnauthorizedError extends WebrpcError {
	constructor(
		name = 'Unauthorized',
		code = 1000,
		message = 'Unauthorized access',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, UnauthorizedError.prototype);
	}
}

export class PermissionDeniedError extends WebrpcError {
	constructor(
		name = 'PermissionDenied',
		code = 1001,
		message = 'Permission denied',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, PermissionDeniedError.prototype);
	}
}

export class SessionExpiredError extends WebrpcError {
	constructor(
		name = 'SessionExpired',
		code = 1002,
		message = 'Session expired',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, SessionExpiredError.prototype);
	}
}

export class MethodNotFoundError extends WebrpcError {
	constructor(
		name = 'MethodNotFound',
		code = 1003,
		message = 'Method not found',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, MethodNotFoundError.prototype);
	}
}

export class RequestConflictError extends WebrpcError {
	constructor(
		name = 'RequestConflict',
		code = 1004,
		message = 'Conflict with target resource',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, RequestConflictError.prototype);
	}
}

export class ServiceDisabledError extends WebrpcError {
	constructor(
		name = 'ServiceDisabled',
		code = 1005,
		message = 'Service disabled',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, ServiceDisabledError.prototype);
	}
}

export class TimeoutError extends WebrpcError {
	constructor(
		name = 'Timeout',
		code = 2000,
		message = 'Request timed out',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, TimeoutError.prototype);
	}
}

export class InvalidArgumentError extends WebrpcError {
	constructor(
		name = 'InvalidArgument',
		code = 2001,
		message = 'Invalid argument',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, InvalidArgumentError.prototype);
	}
}

export class NotFoundError extends WebrpcError {
	constructor(
		name = 'NotFound',
		code = 3000,
		message = 'Resource not found',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, NotFoundError.prototype);
	}
}

export class UserNotFoundError extends WebrpcError {
	constructor(
		name = 'UserNotFound',
		code = 3001,
		message = 'User not found',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, UserNotFoundError.prototype);
	}
}

export class ProjectNotFoundError extends WebrpcError {
	constructor(
		name = 'ProjectNotFound',
		code = 3002,
		message = 'Project not found',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, ProjectNotFoundError.prototype);
	}
}

export class InvalidTierError extends WebrpcError {
	constructor(
		name = 'InvalidTier',
		code = 3003,
		message = 'Invalid subscription tier',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, InvalidTierError.prototype);
	}
}

export class EmailTemplateExistsError extends WebrpcError {
	constructor(
		name = 'EmailTemplateExists',
		code = 3004,
		message = 'Email Template exists',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, EmailTemplateExistsError.prototype);
	}
}

export class SubscriptionLimitError extends WebrpcError {
	constructor(
		name = 'SubscriptionLimit',
		code = 3005,
		message = 'Subscription limit reached',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, SubscriptionLimitError.prototype);
	}
}

export class FeatureNotIncludedError extends WebrpcError {
	constructor(
		name = 'FeatureNotIncluded',
		code = 3006,
		message = 'Feature not included',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, FeatureNotIncludedError.prototype);
	}
}

export class InvalidNetworkError extends WebrpcError {
	constructor(
		name = 'InvalidNetwork',
		code = 3007,
		message = 'Invalid network',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, InvalidNetworkError.prototype);
	}
}

export class InvitationExpiredError extends WebrpcError {
	constructor(
		name = 'InvitationExpired',
		code = 4000,
		message = 'Invitation code is expired',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, InvitationExpiredError.prototype);
	}
}

export class AlreadyCollaboratorError extends WebrpcError {
	constructor(
		name = 'AlreadyCollaborator',
		code = 4001,
		message = 'Already a collaborator',
		status = 0,
		cause?: string,
	) {
		super(name, code, message, status, cause);
		Object.setPrototypeOf(this, AlreadyCollaboratorError.prototype);
	}
}

export enum errors {
	WebrpcEndpoint = 'WebrpcEndpoint',
	WebrpcRequestFailed = 'WebrpcRequestFailed',
	WebrpcBadRoute = 'WebrpcBadRoute',
	WebrpcBadMethod = 'WebrpcBadMethod',
	WebrpcBadRequest = 'WebrpcBadRequest',
	WebrpcBadResponse = 'WebrpcBadResponse',
	WebrpcServerPanic = 'WebrpcServerPanic',
	WebrpcInternalError = 'WebrpcInternalError',
	WebrpcClientDisconnected = 'WebrpcClientDisconnected',
	WebrpcStreamLost = 'WebrpcStreamLost',
	WebrpcStreamFinished = 'WebrpcStreamFinished',
	Unauthorized = 'Unauthorized',
	PermissionDenied = 'PermissionDenied',
	SessionExpired = 'SessionExpired',
	MethodNotFound = 'MethodNotFound',
	RequestConflict = 'RequestConflict',
	ServiceDisabled = 'ServiceDisabled',
	Timeout = 'Timeout',
	InvalidArgument = 'InvalidArgument',
	NotFound = 'NotFound',
	UserNotFound = 'UserNotFound',
	ProjectNotFound = 'ProjectNotFound',
	InvalidTier = 'InvalidTier',
	EmailTemplateExists = 'EmailTemplateExists',
	SubscriptionLimit = 'SubscriptionLimit',
	FeatureNotIncluded = 'FeatureNotIncluded',
	InvalidNetwork = 'InvalidNetwork',
	InvitationExpired = 'InvitationExpired',
	AlreadyCollaborator = 'AlreadyCollaborator',
}

export enum WebrpcErrorCodes {
	WebrpcEndpoint = 0,
	WebrpcRequestFailed = -1,
	WebrpcBadRoute = -2,
	WebrpcBadMethod = -3,
	WebrpcBadRequest = -4,
	WebrpcBadResponse = -5,
	WebrpcServerPanic = -6,
	WebrpcInternalError = -7,
	WebrpcClientDisconnected = -8,
	WebrpcStreamLost = -9,
	WebrpcStreamFinished = -10,
	Unauthorized = 1000,
	PermissionDenied = 1001,
	SessionExpired = 1002,
	MethodNotFound = 1003,
	RequestConflict = 1004,
	ServiceDisabled = 1005,
	Timeout = 2000,
	InvalidArgument = 2001,
	NotFound = 3000,
	UserNotFound = 3001,
	ProjectNotFound = 3002,
	InvalidTier = 3003,
	EmailTemplateExists = 3004,
	SubscriptionLimit = 3005,
	FeatureNotIncluded = 3006,
	InvalidNetwork = 3007,
	InvitationExpired = 4000,
	AlreadyCollaborator = 4001,
}

export const webrpcErrorByCode: { [code: number]: any } = {
	0: WebrpcEndpointError,
	[-1]: WebrpcRequestFailedError,
	[-2]: WebrpcBadRouteError,
	[-3]: WebrpcBadMethodError,
	[-4]: WebrpcBadRequestError,
	[-5]: WebrpcBadResponseError,
	[-6]: WebrpcServerPanicError,
	[-7]: WebrpcInternalErrorError, // Name as per original
	[-8]: WebrpcClientDisconnectedError,
	[-9]: WebrpcStreamLostError,
	[-10]: WebrpcStreamFinishedError,
	1000: UnauthorizedError,
	1001: PermissionDeniedError,
	1002: SessionExpiredError,
	1003: MethodNotFoundError,
	1004: RequestConflictError,
	1005: ServiceDisabledError,
	2000: TimeoutError,
	2001: InvalidArgumentError,
	3000: NotFoundError,
	3001: UserNotFoundError,
	3002: ProjectNotFoundError,
	3003: InvalidTierError,
	3004: EmailTemplateExistsError,
	3005: SubscriptionLimitError,
	3006: FeatureNotIncludedError,
	3007: InvalidNetworkError,
	4000: InvitationExpiredError,
	4001: AlreadyCollaboratorError,
};

//
// Client Implementation for MarketplaceService (relevant part)
//
export type Fetch = (
	input: RequestInfo,
	init?: RequestInit,
) => Promise<Response>;

export class MarketplaceService {
	protected hostname: string;
	protected fetch: Fetch;
	protected path = '/rpc/MarketplaceService/';

	constructor(hostname: string, fetch: Fetch) {
		this.hostname = hostname.replace(/\/*$/, '');
		this.fetch = (input: RequestInfo, init?: RequestInit) => fetch(input, init);
	}

	private url(name: string): string {
		return this.hostname + this.path + name;
	}

	lookupMarketplace = (
		args: LookupMarketplaceArgs,
		headers?: object,
		signal?: AbortSignal,
	): Promise<LookupMarketplaceReturn> => {
		return this.fetch(
			this.url('LookupMarketplace'),
			createHTTPRequest(args, headers, signal),
		).then(
			(res) => {
				return buildResponse(res).then((_data) => {
					return {
						marketplace: <Marketplace>_data.marketplace,
						marketCollections: <Array<MarketCollection>>_data.marketCollections,
						shopCollections: <Array<ShopCollection>>_data.shopCollections,
					};
				});
			},
			(error) => {
				throw WebrpcRequestFailedError.new({
					cause: `lookupMarketplace(): ${error.message || ''}`,
				});
			},
		);
	};
}

//
// Helper Functions
//
const createHTTPRequest = (
	body: object = {},
	headers: object = {},
	signal: AbortSignal | null = null,
): object => {
	const reqHeaders: { [key: string]: string } = {
		...headers,
		'Content-Type': 'application/json',
	};
	reqHeaders[WebrpcHeader] = WebrpcHeaderValue;

	return {
		method: 'POST',
		headers: reqHeaders,
		body: JSON.stringify(body || {}),
		signal,
	};
};

const buildResponse = (res: Response): Promise<any> => {
	return res.text().then((text) => {
		let data;
		try {
			data = JSON.parse(text);
		} catch (error) {
			let message = '';
			if (error instanceof Error) {
				message = error.message;
			}
			throw WebrpcBadResponseError.new({
				status: res.status,
				cause: `JSON.parse(): ${message}: response text: ${text}`,
			});
		}
		if (!res.ok) {
			const code: number = typeof data.code === 'number' ? data.code : 0;
			throw (webrpcErrorByCode[code] || WebrpcError).new(data);
		}
		return data;
	});
};
