/**
 * Error codes for the Sequence Marketplace SDK
 *
 * Organized by category:
 * - TX_*: Transaction-related errors
 * - WALLET_*: Wallet connection/interaction errors
 * - CONFIG_*: Configuration errors
 * - API_*: API/Network request errors
 * - CONTRACT_*: Smart contract interaction errors
 */

export const ErrorCodes = {
	// Transaction errors
	TX_USER_REJECTED: 'TX_USER_REJECTED',
	TX_CHAIN_SWITCH_FAILED: 'TX_CHAIN_SWITCH_FAILED',
	TX_CHAIN_SWITCH_REJECTED: 'TX_CHAIN_SWITCH_REJECTED',
	TX_EXECUTION_FAILED: 'TX_EXECUTION_FAILED',
	TX_SIGNATURE_FAILED: 'TX_SIGNATURE_FAILED',
	TX_CONFIRMATION_FAILED: 'TX_CONFIRMATION_FAILED',
	TX_RECEIPT_NOT_FOUND: 'TX_RECEIPT_NOT_FOUND',
	TX_VALIDATION_FAILED: 'TX_VALIDATION_FAILED',
	TX_INSUFFICIENT_FUNDS: 'TX_INSUFFICIENT_FUNDS',

	// Wallet errors
	WALLET_NOT_CONNECTED: 'WALLET_NOT_CONNECTED',
	WALLET_INSTANCE_NOT_FOUND: 'WALLET_INSTANCE_NOT_FOUND',
	WALLET_CHAIN_ID_UNAVAILABLE: 'WALLET_CHAIN_ID_UNAVAILABLE',

	// Configuration errors
	CONFIG_MISSING: 'CONFIG_MISSING',
	CONFIG_INVALID: 'CONFIG_INVALID',
	CONFIG_MARKETPLACE_NOT_FOUND: 'CONFIG_MARKETPLACE_NOT_FOUND',
	CONFIG_PROJECT_NOT_FOUND: 'CONFIG_PROJECT_NOT_FOUND',
	CONFIG_FETCH_FAILED: 'CONFIG_FETCH_FAILED',

	// Contract/Collection errors
	CONTRACT_INVALID_TYPE: 'CONTRACT_INVALID_TYPE',
	CONTRACT_COLLECTION_NOT_FOUND: 'CONTRACT_COLLECTION_NOT_FOUND',
	CONTRACT_INVALID_CURRENCY: 'CONTRACT_INVALID_CURRENCY',

	// Order/Transaction step errors
	ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
	STEP_INVALID: 'STEP_INVALID',
	STEP_EXECUTION_FAILED: 'STEP_EXECUTION_FAILED',
	STEP_GENERATION_FAILED: 'STEP_GENERATION_FAILED',
	STEP_MISSING_DATA: 'STEP_MISSING_DATA',
	STEP_MISSING_SIGNATURE: 'STEP_MISSING_SIGNATURE',
	STEP_INVALID_SIGNATURE: 'STEP_INVALID_SIGNATURE',
	STEP_MISSING_POST: 'STEP_MISSING_POST',
	STEP_UNEXPECTED: 'STEP_UNEXPECTED',
	STEP_NO_EXECUTION: 'STEP_NO_EXECUTION',
	STEP_NONE_FOUND: 'STEP_NONE_FOUND',

	// Payment/Checkout errors
	PAYMENT_MODAL_FAILED: 'PAYMENT_MODAL_FAILED',
	PAYMENT_TRANSACTION_FAILED: 'PAYMENT_TRANSACTION_FAILED',
	CHECKOUT_OPTIONS_FAILED: 'CHECKOUT_OPTIONS_FAILED',

	// Unknown/Unsupported
	UNKNOWN_TRANSACTION_TYPE: 'UNKNOWN_TRANSACTION_TYPE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
