name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Typecheck and Test
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Typecheck
        run: pnpm check

      - name: Test
        run: pnpm test
