name: Typecheck and Test

on: [push]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Typecheck
        run: pnpm check
  
  eslint:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: ESLint
        run: pnpm eslint

  test-changed:
    name: Test Changed
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: git-checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Test
        run: |
          CHANGED_FILES=$(git diff --name-only origin/master...HEAD | grep '\.test\.' || true)
          if [ -n "$CHANGED_FILES" ]; then
            # Process each file to make path relative to sdk directory
            PROCESSED_FILES=""
            for file in $CHANGED_FILES; do
              if [[ $file == sdk/* ]]; then
                # Remove 'sdk/' prefix to make path relative to sdk directory
                RELATIVE_PATH="${file#sdk/}"
                PROCESSED_FILES="$PROCESSED_FILES $RELATIVE_PATH"
              fi
            done
            
            if [ -n "$PROCESSED_FILES" ]; then
              cd sdk && pnpm test $PROCESSED_FILES
            else
              echo "No valid test files found."
            fi
          else
            echo "No changed test files to run."
          fi

  test-all:
    name: Test All
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Test
        run: pnpm test
