name: Publish Pre-release

on: [push]
  # workflow_dispatch:
  # push:
  #   branches:
  #     - pre-release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-dependencies

      - name: Build SDK
        run: pnpm run build

      - name: Publish to pre-release branch
        run: |
          # Prepare dist directory
          mkdir -p /tmp/marketplace-sdk
          cp -r sdk/dist/* /tmp/marketplace-sdk/
          cp sdk/package.json /tmp/marketplace-sdk/
          cp README.md /tmp/marketplace-sdk/

          # Initialize git in dist directory
          cd /tmp/marketplace-sdk
          git init
          git checkout -b pre-release

          # Configure git
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Commit and push
          git add .
          git commit -m "Build: publish marketplace-sdk pre-release"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin HEAD:pre-release